### ISSUE TITLE
How to integrate cloud-init to run user data at launch

### ISSUE THREAD

**Issue by brokedba** [oracle/oci-ansible-modules#127]
## Issue Report

**Describe the issue**

 I wanted to know how to integrate cloud-init to run command on bootstrap . I know there is a metadata method but it only manages ssh keys it seems  and uses the command module to test the access but I want to install nginx and have the index content  loaded. I did that in terraform .
is something like this possible ?  using command module is not really optimal. thanks
```
 metadata:
   ssh_authorized_keys: "{{ lookup('file',  my_test_public_key ) }}"
   user_data: "{{ lookup('file', '{{ cloud_init_file }}' ) }}"
 delegate_to: localhost
```
 

**Environment**

* OS version:
ubuntu 
* Ansible version:

``` ansible 2.9.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/koss/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Apr 15 2020, 17:07:12) [GCC 5.4.0 20160609] ``` 

* OCI Python SDK version:

 `2.14.0` 

* OCI Ansible Modules version:

oracle.oci_ansible_modules (v1.18.0)
