### ISSUE TITLE
The OCI Dynamic Inventory Plugin outputs verbosely revealing secret information contained within userdata.

### ISSUE THREAD

**Issue by AndreasFrangopoulos** [oracle/oci-ansible-modules#129]
## Issue Report

**Describe the issue**

The OCI Dynamic Inventory Plugin outputs verbosely revealing secret information contained within userdata.

We use the Dynamic Inventory Plugin to enumerate resources in an Azure DevOps pipeline before running Ansible playbooks against them. The script works well but there are is a "Warning" posted for every instance queried against my filter with the messages if they don't match the filter:
```
2020-07-21T08:49:14.5353801Z [WARNING]: Instances in compartment ocid1.compartment.oc1..aaaaaaaaygxxxxxxl
2020-07-21T08:49:14.5354695Z rulshxxxxxxxugbuny67fnc2ogad2orv4legyvvoa which match all the freeform tags: []

```
For instances that match the filter, all the metadata is posted including, unfortunately, the userdata base64 encoded CLoudInit scripts which, in our case, holds secret information we use to configure local admins. Obviously, we don't want this information sitting in a web based log.

I can't seem to find a configuration option that will allow us to suppress this output.

**Expected behavior**

Configuration option to suppress output of instance details.

**Environment**

* OS version:
Ubuntu 20.02

* Ansible version:

```
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/azureagent/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.2 (default, Apr 27 2020, 15:53:34) [GCC 9.3.0]

```
* OCI Python SDK version:

   2.17.2

* OCI Ansible Modules version:

**Ansible playbook to reproduce the issue**

```
 # Optional fields to specify oci connection config:
config_file: /home/agent/temp/config
config_profile: DEFAULT

# Enable threads to speedup lookup
enable_parallel_processing: yes

plugin: oci

regions:
- us-ashburn-1

keyed_groups:
  # add hosts to tag_Name_value groups for each oci host's tags.Name variable
  - key: tags.Name
    prefix: tag_Name_

filters:
- freeform_tags: {
  "ansible_managed" : "true"
}
```
