### ISSUE TITLE
how to launch instance with vnic type 'pv' using oci_instance?

### ISSUE THREAD

**Issue by vburamdo** [oracle/oci-ansible-modules#131]
how to launch instance with vnic type 'pv' using oci_instance?

**Comment by AmeyaLokre** [comment]
Hello @vburamdo , this feature is not supported in our old [oci-ansible-modules](https://github.com/oracle/oci-ansible-modules) but this feature is supported in our new [oci-ansible-collection](https://github.com/oracle/oci-ansible-collection) modules. An instance with vnic type ParaVirtualized can be launched using the module `oci_compute_instance` module with the parameter `launch_options` like the following:
```
  oci_compute_instance:
    display_name: myinstance1
    availability_domain: Uocm:PHX-AD-1
    compartment_id: ocid1.compartment.oc1..xxxxxEXAMPLExxxxx...vm62xq
    shape: VM.Standard2.1
    .
    .
    launch_options:
       network_type: "PARAVIRTUALIZED"
```

Use the command `ansible-doc oracle.oci.oci_compute_instance` to have a more detailed look at the available parameter options

The old [oci-ansible-modules](https://github.com/oracle/oci-ansible-modules) are getting replaced and is now only in maintenance mode. These will be deprecated by mid-2021 and we would recommend you to use the new [oci-ansible-collections](https://github.com/oracle/oci-ansible-collection). New features will be supported faster in the new [oci-ansible-collections](https://github.com/oracle/oci-ansible-collection).
Refer to the [Migration Guide](https://github.com/oracle/oci-ansible-collections/blob/master/MigrationGuide.md) for best migration practices.
