### ISSUE TITLE
oci_security_list not idempotent

### ISSUE THREAD

**Issue by parkerbp** [oracle/oci-ansible-modules#31]
## Issue Report

**Describe the issue**

If you issue the same oci_security_list command twice it fails on the second attempt if you do not specify values for both ingress_security_rules and egress_security_rules. 

So you cannot create an empty security list, like you can with route tables.

Reproducible with example from documentation with the below changes:
 - change the min and max values to int instead of strings which they should be
 - remove the defined tag as does not exist in my env
 - comment out the egress or ingress rule block

```
    - name: Create a security list with rules
      oci_security_list:
        name: 'ansible_sec_list'
        compartment_id: 'ocid.compartment..xxxxxEXAMPLExxxxx'
        vcn_id: 'ocid1.vcn..xxxxxEXAMPLExxxxx'
        state: 'present'
        freeform_tags:
            region: 'east'
        ingress_security_rules:
          - source: '0.0.0.0/0'
            is_stateless: False
            protocol: '6'
            tcp_options:
                destination_port_range:
                    min: 22
                    max: 22
          - source: 'oci-iad-objectstorage'
            source_type: 'SERVICE_CIDR_BLOCK'
            is_stateless: False
            protocol: '6'
          - source: '0.0.0.0/0'
            is_stateless: False
            protocol: '1'
            icmp_options:
                code: 4
                type: 3
    #    egress_security_rules:
    #        - destination: '0.0.0.0/0'
    #          protocol: 'all'
```

On the first run security list is created successfully. On the second run it fails.

Same issues if you leave the egress line in there but remove the definitions

**Expected behavior**

Should be able to create a SL with no rules (which you can) however should report OK on the second run.

**Environment**

* OS version: NA

* Ansible version: 

```
  ansible 2.8.0.dev0
  config file = /home/admin/Projects/cloud-provisioning/oci_ansible/ansible.cfg
  configured module search path = ['/home/admin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.6 (default, Aug 31 2018, 01:10:26) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28.0.1)]
```

* OCI Python SDK version:

    2.2.1

* OCI Ansible Modules version:

    1.6.0

**Ansible playbook to reproduce the issue**

   see disc

**Comment by manojmeda** [comment]
@parkerbp Thanks for raising this. I am able to reproduce the issue. We will check and update this issue when the fix is available.

**Comment by manojmeda** [comment]
@parkerbp Actually ingress_security_rules and egress_security_rules are required attributes for creating a security list. They can be an empty list though. So we will make them required attributes in the next release and if you wish to create without rules, you can just pass an empty list as shown below:

ingress_security_rules: []
egress_security_rules: []

**Comment by parkerbp** [comment]
@manojmeda following this logic

1. Create list with no rules
2. Add rules to this list
3. Re-run code for step 1

Step 3 will remove remove the rules from the security list as such the idempotentcy is broken as it should be at a list level, not at the rules level. Route tables work correctly.

**Comment by gauravjain000** [comment]
@parkerbp I am the product manager for Ansible module. Thanks for your feedback. If we have not connected before, I would love to do so understand 1. your usecase 2. how we can we make the experience better for you. I can be contacted on g.gaurav.j.jain@oracle.com.
Thanks,
Gaurav

**Comment by manojmeda** [comment]
@parkerbp Step 3 would actually create a new security list. Same with route tables. Idempotence is at the list level and so the step 3 in both cases would create a new resource as it does not match the existing resource.

**Comment by parkerbp** [comment]
@manojmeda I believe you are incorrect on this point which can be seen in this example.
[output.txt](https://github.com/oracle/oci-ansible-modules/files/3037817/output.txt)


The idea should be that you are able to add and remove rules from the security list without affecting the list itself. Below is a use case for route tables which is how it should behave:

 ```
 - name: create the route tables
    oci_route_table:
      compartment_id: "ocid1.compartment.oc1....."
      vcn_id: "ocid1.vcn.oc1....."
      name: "myroute_tab"
    register: result

  - name: Add the IG rules to the route table
    oci_route_table:
      compartment_id: "ocid1.compartment.oc1....."
      vcn_id: "ocid1.vcn.oc1...."
      rt_id: "{{ result.route_table.id }}"
      delete_route_rules: no
      route_rules:
        - cidr_block: "0.0.0.0/0"
          network_entity_id: "ocid1.internetgateway....."

  - name: create the route tables
    oci_route_table:
      compartment_id: "ocid1.compartment.oc1....."
      vcn_id: "ocid1.vcn.oc1...."
      name: "myroute_tab"
    register: result
```
I have attached the output, the third step doesn't change anything as the route table itself is already created. The rule that was added in step 2 is still present etc.

**Comment by manojmeda** [comment]
@parkerbp I was talking about the scenario where you explicitly specify empty rules as shown below:
```
- name: create the route tables
   oci_route_table:
     compartment_id: "ocid1.compartment.oc1....."
     vcn_id: "ocid1.vcn.oc1....."
     name: "myroute_tab"
    route_rules: []
   register: result

 - name: Add the IG rules to the route table
   oci_route_table:
     compartment_id: "ocid1.compartment.oc1....."
     vcn_id: "ocid1.vcn.oc1...."
     rt_id: "{{ result.route_table.id }}"
     delete_route_rules: no
     route_rules:
       - cidr_block: "0.0.0.0/0"
         network_entity_id: "ocid1.internetgateway....."

 - name: create the route tables
   oci_route_table:
     compartment_id: "ocid1.compartment.oc1....."
     vcn_id: "ocid1.vcn.oc1...."
     name: "myroute_tab"
     route_rules: []
   register: result
```
The problem is that `ingress_security_rules` and `egress_security_rules` are required for creating a security list where as `route_rules` is not for creating a route table.
