### ISSUE TITLE
Upper case causes idempotence to break with VCNs

### ISSUE THREAD

**Issue by parkerbp** [oracle/oci-ansible-modules#32]
## Issue Report

Creating a VCN in upper case causes  idempotence to break, running the same command twice produces two identical VCNs. Lower case names are fine.

```
- name: Create a VCN
    oci_vcn:
      cidr_block: '10.6.0.0/16'
      compartment_id: 'ocid1.compartment.oc1..fgfgf'
      display_name: MY_VCN
      dns_label: ansiblevcn
```

**Expected behavior**

No change on second run

**Environment**

* OS version: NA

* Ansible version:

  ansible 2.8.0.dev0
  config file = /home/admin/Projects/cloud-provisioning/oci_ansible/ansible.cfg
  configured module search path = ['/home/admin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.6 (default, Aug 31 2018, 01:10:26) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28.0.1)]

* OCI Python SDK version:

2.2.1

* OCI Ansible Modules version:

1.6.0

**Ansible playbook to reproduce the issue**

see disc
