### ISSUE TITLE
Cannot get the IP address of a mount target

### ISSUE THREAD

**Issue by tyskjohan** [oracle/oci-ansible-modules#39]
## Issue Report

````
PLAY [localhost] **********************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Get instance metadata] **********************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Get all mount targets] **********************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Get all private ips] ************************************************************************************************************************************************************************************************************
failed: [localhost] (item={u'lifecycle_state': u'ACTIVE', u'availability_domain': u'orBF:EU-FRANKFURT-1-AD-2', u'display_name': u'OAG', u'private_ip_ids': [u'ocid1.privateip.oc1.eu-frankfurt-1.abtheljtdwuxv5ollxb5vfrqfwz3h6c34a3fde32ulzh3xqsl6kos3m7szjq'], u'compartment_id': u'ocid1.compartment.oc1..aaaaaaaaxwpjh3ahcxmkdrimeo5ehkhx4ekizxcjwxcj35spnsvrx5frzn7a', u'export_set_id': u'ocid1.exportset.oc1.eu_frankfurt_1.aaaaacvippxgefsnmzzgcllqojxwiotfouwwm4tbnzvwm5lsoqwtcllbmqwtgaaa', u'defined_tags': {}, u'freeform_tags': {u'tier': u'OAG', u'environment': u'ocitest0'}, u'time_created': u'2019-04-04T19:39:22.014000+00:00', u'subnet_id': u'ocid1.subnet.oc1.eu-frankfurt-1.aaaaaaaarprgvketeanr25qexwnhfdvfb42wsq35x6onkc7jjmdzj54rh6xa', u'lifecycle_details': u'', u'id': u'ocid1.mounttarget.oc1.eu_frankfurt_1.aaaaacvippxgefsomzzgcllqojxwiotfouwwm4tbnzvwm5lsoqwtcllbmqwtgaaa'}) => {"changed": false, "item": {"availability_domain": "orBF:EU-FRANKFURT-1-AD-2", "compartment_id": "ocid1.compartment.oc1..aaaaaaaaxwpjh3ahcxmkdrimeo5ehkhx4ekizxcjwxcj35spnsvrx5frzn7a", "defined_tags": {}, "display_name": "OAG", "export_set_id": "ocid1.exportset.oc1.eu_frankfurt_1.aaaaacvippxgefsnmzzgcllqojxwiotfouwwm4tbnzvwm5lsoqwtcllbmqwtgaaa", "freeform_tags": {"environment": "ocitest0", "tier": "OAG"}, "id": "ocid1.mounttarget.oc1.eu_frankfurt_1.aaaaacvippxgefsomzzgcllqojxwiotfouwwm4tbnzvwm5lsoqwtcllbmqwtgaaa", "lifecycle_details": "", "lifecycle_state": "ACTIVE", "private_ip_ids": ["ocid1.privateip.oc1.eu-frankfurt-1.abtheljtdwuxv5ollxb5vfrqfwz3h6c34a3fde32ulzh3xqsl6kos3m7szjq"], "subnet_id": "ocid1.subnet.oc1.eu-frankfurt-1.aaaaaaaarprgvketeanr25qexwnhfdvfb42wsq35x6onkc7jjmdzj54rh6xa", "time_created": "2019-04-04T19:39:22.014000+00:00"}, "msg": "Either Floating Private IP with ID ['ocid1.privateip.oc1.eu-frankfurt-1.abtheljtdwuxv5ollxb5vfrqfwz3h6c34a3fde32ulzh3xqsl6kos3m7szjq'] does not exist or you are not authorized to access it."}
failed: [localhost] (item={u'lifecycle_state': u'ACTIVE', u'availability_domain': u'orBF:EU-FRANKFURT-1-AD-2', u'display_name': u'OSB', u'private_ip_ids': [u'ocid1.privateip.oc1.eu-frankfurt-1.abtheljtrqjybcdfcy3drcssnwkbas5zmnsu4iw53g7fjy2glb3scs4g6lia'], u'compartment_id': u'ocid1.compartment.oc1..aaaaaaaaxwpjh3ahcxmkdrimeo5ehkhx4ekizxcjwxcj35spnsvrx5frzn7a', u'export_set_id': u'ocid1.exportset.oc1.eu_frankfurt_1.aaaaaa4np2snihtmmzzgcllqojxwiotfouwwm4tbnzvwm5lsoqwtcllbmqwtgaaa', u'defined_tags': {}, u'freeform_tags': {u'tier': u'OSB', u'environment': u'ocitest0'}, u'time_created': u'2019-03-28T11:06:07.340000+00:00', u'subnet_id': u'ocid1.subnet.oc1.eu-frankfurt-1.aaaaaaaarprgvketeanr25qexwnhfdvfb42wsq35x6onkc7jjmdzj54rh6xa', u'lifecycle_details': u'', u'id': u'ocid1.mounttarget.oc1.eu_frankfurt_1.aaaaaa4np2snihtnmzzgcllqojxwiotfouwwm4tbnzvwm5lsoqwtcllbmqwtgaaa'}) => {"changed": false, "item": {"availability_domain": "orBF:EU-FRANKFURT-1-AD-2", "compartment_id": "ocid1.compartment.oc1..aaaaaaaaxwpjh3ahcxmkdrimeo5ehkhx4ekizxcjwxcj35spnsvrx5frzn7a", "defined_tags": {}, "display_name": "OSB", "export_set_id": "ocid1.exportset.oc1.eu_frankfurt_1.aaaaaa4np2snihtmmzzgcllqojxwiotfouwwm4tbnzvwm5lsoqwtcllbmqwtgaaa", "freeform_tags": {"environment": "ocitest0", "tier": "OSB"}, "id": "ocid1.mounttarget.oc1.eu_frankfurt_1.aaaaaa4np2snihtnmzzgcllqojxwiotfouwwm4tbnzvwm5lsoqwtcllbmqwtgaaa", "lifecycle_details": "", "lifecycle_state": "ACTIVE", "private_ip_ids": ["ocid1.privateip.oc1.eu-frankfurt-1.abtheljtrqjybcdfcy3drcssnwkbas5zmnsu4iw53g7fjy2glb3scs4g6lia"], "subnet_id": "ocid1.subnet.oc1.eu-frankfurt-1.aaaaaaaarprgvketeanr25qexwnhfdvfb42wsq35x6onkc7jjmdzj54rh6xa", "time_created": "2019-03-28T11:06:07.340000+00:00"}, "msg": "Either Floating Private IP with ID ['ocid1.privateip.oc1.eu-frankfurt-1.abtheljtrqjybcdfcy3drcssnwkbas5zmnsu4iw53g7fjy2glb3scs4g6lia'] does not exist or you are not authorized to access it."}
        to retry, use: --limit @/home/opc/ansible/elhub-oci.retry

````

**Expected behavior**

`oci_private_ips` contains the ipv4 addresses needed to reach the mount targets.

**Environment**

* OS version:
Oracle Linux Server release 7.6

* Ansible version:

ansible 2.7.9
  config file = /home/opc/.ansible.cfg
  configured module search path = [u'/home/opc/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov  1 2018, 03:12:47) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36.0.1)]

* OCI Python SDK version:

2.2.4

* OCI Ansible Modules version:

1.6.0

**Ansible playbook to reproduce the issue**

Trying to run:

````
---
# 
- hosts: localhost
  tasks:
  - name: Get instance metadata
    uri:
      url: http://169.254.169.254/opc/v1/instance/
      return_content: yes
    register: instance_metadata

  - name: Get all mount targets
    oci_mount_target_facts:
      compartment_id: "{{ instance_metadata.json.compartmentId }}"
      availability_domain: "{{ instance_metadata.json.availabilityDomain }}"
    register: oci_mount_targets

  - name: Get all private ips
    oci_private_ip_facts:
      private_ip_id: "{{ item.private_ip_ids }}"
    loop: "{{ oci_mount_targets.mount_targets }}"
    register: oci_private_ips

````

**Comment by tyskjohan** [comment]
BTW this works fine from the command line:

````
[root@bastion ~]# oci fs mount-target list --availability-domain orBF:EU-FRANKFURT-1-AD-2 --compartment-id ocid1.compartment.oc1..aaaaaaaaxwpjh3ahcxmkdrimeo5ehkhx4ekizxcjwxcj35spnsvrx5frzn7a
{
  "data": [
    {
      "availability-domain": "orBF:EU-FRANKFURT-1-AD-2",
      "compartment-id": "ocid1.compartment.oc1..aaaaaaaaxwpjh3ahcxmkdrimeo5ehkhx4ekizxcjwxcj35spnsvrx5frzn7a",
      "display-name": "OAG",
      "export-set-id": "ocid1.exportset.oc1.eu_frankfurt_1.aaaaacvippxgefsnmzzgcllqojxwiotfouwwm4tbnzvwm5lsoqwtcllbmqwtgaaa",
      "id": "ocid1.mounttarget.oc1.eu_frankfurt_1.aaaaacvippxgefsomzzgcllqojxwiotfouwwm4tbnzvwm5lsoqwtcllbmqwtgaaa",
      "lifecycle-state": "ACTIVE",
      "private-ip-ids": [
        "ocid1.privateip.oc1.eu-frankfurt-1.abtheljtdwuxv5ollxb5vfrqfwz3h6c34a3fde32ulzh3xqsl6kos3m7szjq"
      ],
      "subnet-id": "ocid1.subnet.oc1.eu-frankfurt-1.aaaaaaaarprgvketeanr25qexwnhfdvfb42wsq35x6onkc7jjmdzj54rh6xa",
      "time-created": "2019-04-04T19:39:22.014000+00:00"
    },
    {
      "availability-domain": "orBF:EU-FRANKFURT-1-AD-2",
      "compartment-id": "ocid1.compartment.oc1..aaaaaaaaxwpjh3ahcxmkdrimeo5ehkhx4ekizxcjwxcj35spnsvrx5frzn7a",
      "display-name": "OSB",
      "export-set-id": "ocid1.exportset.oc1.eu_frankfurt_1.aaaaaa4np2snihtmmzzgcllqojxwiotfouwwm4tbnzvwm5lsoqwtcllbmqwtgaaa",
      "id": "ocid1.mounttarget.oc1.eu_frankfurt_1.aaaaaa4np2snihtnmzzgcllqojxwiotfouwwm4tbnzvwm5lsoqwtcllbmqwtgaaa",
      "lifecycle-state": "ACTIVE",
      "private-ip-ids": [
        "ocid1.privateip.oc1.eu-frankfurt-1.abtheljtrqjybcdfcy3drcssnwkbas5zmnsu4iw53g7fjy2glb3scs4g6lia"
      ],
      "subnet-id": "ocid1.subnet.oc1.eu-frankfurt-1.aaaaaaaarprgvketeanr25qexwnhfdvfb42wsq35x6onkc7jjmdzj54rh6xa",
      "time-created": "2019-03-28T11:06:07.340000+00:00"
    }
  ]
}
[root@bastion ~]# oci network private-ip get --private-ip-id ocid1.privateip.oc1.eu-frankfurt-1.abtheljtdwuxv5ollxb5vfrqfwz3h6c34a3fde32ulzh3xqsl6kos3m7szjq
{
  "data": {
    "availability-domain": "orBF:EU-FRANKFURT-1-AD-2",
    "compartment-id": "ocid1.compartment.oc1..aaaaaaaaxwpjh3ahcxmkdrimeo5ehkhx4ekizxcjwxcj35spnsvrx5frzn7a",
    "defined-tags": {},
    "display-name": "privateip20190404193929",
    "freeform-tags": {},
    "hostname-label": null,
    "id": "ocid1.privateip.oc1.eu-frankfurt-1.abtheljtdwuxv5ollxb5vfrqfwz3h6c34a3fde32ulzh3xqsl6kos3m7szjq",
    "ip-address": "10.123.10.79",
    "is-primary": false,
    "subnet-id": "ocid1.subnet.oc1.eu-frankfurt-1.aaaaaaaarprgvketeanr25qexwnhfdvfb42wsq35x6onkc7jjmdzj54rh6xa",
    "time-created": "2019-04-04T19:39:29.356000+00:00",
    "vnic-id": "ocid1.vnic.oc1.eu-frankfurt-1.abtheljti3xdqm7q2twnxgt4yj2ivbxdf7laqbjiffnbqxsxfdll6mnz4xyq"
  },
  "etag": "90c4f908"
}
````

**Comment by tyskjohan** [comment]
Reproduced with newer versions:

````
[opc@elhansible1-ocitest0 ansible]$ python -c "import oci;print(oci.__version__)"
2.2.5
[opc@elhansible1-ocitest0 ansible]$ python -c "from ansible.module_utils.oracle import oci_utils; print(oci_utils.__version__)"
1.7.0
````

**Comment by manojmeda** [comment]
@tyskjohan `private_ip_ids` is a list as a mount target can have multiple private ips. So you need to access a specific element (for ex: item.private_ip_ids[0]) or loop through it to get all the private ips. Please refer below on how you can do this.

```
---
# 
- hosts: localhost
  tasks:
  - name: Get instance metadata
    uri:
      url: http://169.254.169.254/opc/v1/instance/
      return_content: yes
    register: instance_metadata

  - name: Get all mount targets
    oci_mount_target_facts:
      compartment_id: "{{ instance_metadata.json.compartmentId }}"
      availability_domain: "{{ instance_metadata.json.availabilityDomain }}"
    register: oci_mount_targets

  - name: Get all private ips
    oci_private_ip_facts:
      private_ip_id: "{{ item.1 }}"
    loop: "{{ oci_mount_targets.mount_targets | subelements('private_ip_ids') }}"
    register: oci_private_ips

```
