### ISSUE TITLE
Issue :  Not able to delete a specific security rule using oci_security_list module

### ISSUE THREAD

**Issue by vbulusu16** [oracle/oci-ansible-modules#69]
## Issue Report

While using oci_security_list module we are able to add the security rule ( ingress or egress) in a specific security list but not able delete a specific existing rule.. 

**Expected behavior**

we were not able to assign "state: absent" for a security rule . It is considering the State atribute for the security List 

**Error**
fatal: [localhost -> localhost]: FAILED! => {
   "changed": false,
   "invocation": {
       "module_args": {
           "api_user": null,
           "api_user_fingerprint": null,
           "api_user_key_file": null,
           "api_user_key_pass_phrase": null,
           "auth_type": "api_key",
           "compartment_id": null,
           "config_file_location": "xxxxxxxx",
           "config_profile_name": "xxxxxx",
           "defined_tags": null,
           "delete_security_rules": false,
           "display_name": null,
           "egress_security_rules": null,
           "force_create": false,
           "freeform_tags": null,
           "ingress_security_rules": [
               {
                   "is_stateless": false,
                   "protocol": "6",
                   "source": "xxxxxxxx",
                   "tcp_options": {
                       "destination_port_range": {
                           "max": 111,
                           "min": 111
                       }
                   }
               }
           ],
           "key_by": null,
           "purge_security_rules": false,
           "region": null,
           "security_list_id": "ocid1.securitylist.oc1.xxxxxxxxxxx",
           "state": "absent",
           "tenancy": null,
           "vcn_id": null,
           "wait": true,
           "wait_timeout": 1200,
           "wait_until": null
       }
   },
   "msg": "ocid1.securitylist.oc1.phx.xxxxxxxxxxxxxxx is associated with subnet security list association that is in use"
}

**Environment**

* OS version:
  Linux 7.6

* Ansible version:

   ansible 2.7.9

* OCI Python SDK version:

    2.2.19

* OCI Ansible Modules version:
1.10.0

**Ansible playbook to reproduce the issue**

    - name: 'delete the rule on SL-XXXXXXXXX-01'
     delegate_to: localhost
     oci_security_list:
       security_list_id:  "ocid1.securitylist.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
       purge_security_rules: 'no'
       state: 'absent'
       config_file_location: "XXXXXXXXXXXXXXXXXXX"
       config_profile_name:  "XXXXXXXXXXXXXXX"
       ingress_security_rules:
         - source: "XXXXXXXXXXXX"
           is_stateless: False
           protocol: "6"
           tcp_options:
             destination_port_range:
                   min: 111
                   max: 111

**Comment by nalsaber** [comment]
It seems you need to delete the subnet first. If the security list is associated with a subnet, you can't delete it.  You can check this behavior in the console also.

**Comment by nalsaber** [comment]
We don't currently support deleting security_rules. You have to delete the security_list.

**Comment by manojmeda** [comment]
@vbulusu16 You can use the module option `delete_security_rules` to delete specific security rules from a security list. Below is an example to delete a specific security rule:
```
- name: Update a security list by deleting existing ingress rules
  oci_security_list:
    security_list_id: 'ocid1.securitylist.xxxxxEXAMPLExxxxx'
    ingress_security_rules:
        - source: '10.0.0.0/8'
          is_stateless: False
          protocol: '6'
          tcp_options:
              destination_port_range:
                 min: 25
                 max: 30
    delete_security_rules: 'yes'
    state: 'present'
```
In the above case, the given ingress security rules would be deleted from the security list if they exist.
