### ISSUE TITLE
Module oci_user doesn't update group 

### ISSUE THREAD

**Issue by zdudic** [oracle/oci-ansible-modules#7]
I believe this module doesn't update user's group, and I have not tested update of other user's properties. Here is playbook that creates two users: 

-name : Users playbook for creating and other modification
  connection: local
  hosts: localhost
  tasks:
     -name: Create User with ui password and  group memberships (LV tenancy)
       oci_user:
          name: "{{item.name}}"    
          description: "{{item.description}}"
          user_groups: "{{item.groups}}"     
          create_or_reset_ui_password: True
          state: 'present'
       loop:    
            -{ name: zarko1, groups: "SysAdmins.grp", description: 'local account' }
            -{ name: zarko2, groups: 'labops.admins.grp', description: 'local account' }

The success result is:

changed: [localhost] => (item={u'name': u'zarko1', u'groups': u'SysAdmins.grp', u'description': u'local account'})
changed: [localhost] => (item={u'name': u'zarko2', u'groups': u'labops.admins.grp', u'description': u'local account'})

Then I swap groups between two users, like this:

-{ name: zarko1, groups: "labops.admins.grp", description: 'local account' }
-{ name: zarko2, groups: 'SysAdmins.grp', description: 'local account' }

... and run playbook again. Result reads that change is not made. 

ok: [localhost] => (item={u'name': u'zarko1', u'groups': u'SysAdmins.grp', u'description': u'local account'})
ok: [localhost] => (item={u'name': u'zarko2', u'groups': u'labops.admins.grp', u'description': u'local account'})

**Comment by debayan-gupta** [comment]
Thanks for using OCI Ansible Modules and providing your valuable feedback. We'll investigate this issue and get back yo you ASAP. One humble request, in future, please fill up the issue template with all the details e.g OCI SDK version, Ansible version etc which will be very helpful for us to tackle the issue more efficiently.

**Comment by debayan-gupta** [comment]
The example playbook is for creating users and associating them with some group. For updating user's group association, a separate playbook with proper input is required. Also, it is recommended to provide group information input in a list. Following are the examples:

User Creation Playbook
-------------------------------
```yaml
- name : Users playbook for creating new users
  connection: local
  hosts: localhost
  tasks:
    - name: Create User with ui password and group memberships (LV tenancy)
      oci_user:
         name: "{{item.name}}"
         description: "{{item.description}}"
         user_groups: "{{item.groups}}"
         create_or_reset_ui_password: True
         state: 'present'
      loop:
         - { name: zarko1, groups: ['labops.admins.grp'], description: 'local account' }
         - { name: zarko2, groups: ['SysAdmins.grp'], description: 'local account' }
```
Updating User's Group Association Playbook
--------------------------------------------------------
```yaml
- name : Users playbook for updating user's group association
  connection: local
  hosts: localhost
  tasks:
    - name: Update User's group association (LV tenancy)
      oci_user:
         id: "{{item.id}}"
         description: "{{item.description}}"
         user_groups: "{{item.groups}}"
         create_or_reset_ui_password: True
         state: 'present'
      loop:
         - { id: 'ocid1.user.oc1..xxx', groups: ['SysAdmins.grp'], description: 'local account' }
         - { id: 'ocid1.user.oc1..xxx', groups: ['labops.admins.grp'], description: 'local account' }
```
For any update scenario, please use 'id' of that specific resource as input. You can get 'id' from user's fact module. Feel free to check our example page which provides example for different use cases related to OCI User [here](https://oracle-cloud-infrastructure-ansible-modules.readthedocs.io/en/latest/modules/oci_user_module.html#oci-user-module). 

Also, in the provided example, user's group association would be appended to the new group i.e. user 'zarco1' would be associated with both 'labops.admins.grp' and 'SysAdmins.grp'. In case you want to replace the group association, please provide the input 'purge_group_memberships: True' explicitly, which is 'False' by default.

Please try the example and get back to us if the issue persists. We would like to hear more from you about your experience with OCI Ansible modules. Thanks.
