### ISSUE TITLE
Add ability to use filters in facts modules

### ISSUE THREAD

**Issue by rishimahajan** [oracle/oci-ansible-modules#91]
## Issue Report

**Describe the issue**
This is an enhancement request
In order to fetch facts for database systems with tag, currently i have to use json_query
```
- name: Fetch facts for db systems in compartment
  oci_db_system_facts:
    compartment_id: "ocid1.compartment.oc1..aaaaaaaa"
  register: db_system_facts

- name: Set facts for database systems with {{tag.namespace}}.{{tag.key}}={{tag.value}} to be patched
  set_fact:
    db_system_id: "{{ db_system_facts | json_query(server_query) }}"
  vars:
    server_query: "results[*].db_systems[?defined_tags.{{ tag.namespace }}.{{ tag.key }}=='{{ tag.value }}'].id | []"
```

**Expected behavior**
Availability of a filter expression can do it like this and make it much easier.
```
- name: Fetch facts for db systems in compartment
  oci_db_system_facts:
    filter: 
      "tag:operations.environment": "test"  
  register: db_system_facts

Similarly, db systems in a specific availability domain should be fetched using filter on availability_domain.
- name: List all DB System in a availability domain
  oci_db_system_facts:
    filter:
         availability_domain: "xxxxxxx"
```

Although i have shared an example for databases, this is required for all services.

**Environment**

* OS version:
Oracle Linux Server release 7.7
* Ansible version:
ansible 2.8.4
* OCI Python SDK version:
2.6.5
* OCI Ansible Modules version:
1.12.0
**Ansible playbook to reproduce the issue**

    insert a sample playbook to reproduce the issue here(if relevant to the issue)
