### ISSUE TITLE
Add ability to skip DELETED compartments in oci_compartment_facts module

### ISSUE THREAD

**Issue by rishimahajan** [oracle/oci-ansible-modules#95]
## Issue Report

**Describe the issue**

Currently there is no option in **oci_compartment_facts** module to skip fetching "DELETED" compartments. Due to this, the module will always fetch "DELETED" compartments and any modules relying on this module to scan resources in fetched compartments will fail.

**Expected behavior**

oci_compartment_facts should provide an option to skip DELETED compartments on the basis of "lifecycle_state".

**Environment**

* OS version:
Oracle Linux Server release 7.7

* Ansible version:
ansible 2.8.4

* OCI Python SDK version:
2.6.5

* OCI Ansible Modules version:
1.14.0

**Ansible playbook to reproduce the issue**
```
- name: Scanning compartments
  oci_compartment_facts:
    compartment_id: "<tenancy_ocid>"
    depth: 100
  register: compartment_facts

- name: Fetch database systems with tag {{tag.namespace}}.{{tag.key}}={{tag.value}} in scanned compartments
  oci_db_system_facts:
    compartment_id: "{{ item.id }}"
  loop: "{{ compartment_facts.compartments }}"
  register: all_db_system_facts
```
As oci_compartment_facts doesn't have option to skip "DELETED" compartments, oci_db_system_facts module fails to fetch resources from "DELETED" compartment.

As a workaround i can added ignore_errors in task but a better solution would be to have an option to skip using lifecycle_state of compartment in module.
```
failed: [localhost] (item={u'lifecycle_state': u'DELETED', u'inactive_status': None, u'name': u'dbcomp2.pIe8M9rc', u'compartment_id': u'ocid1.compartment.oc1..xxxxx', u'is_accessible': None, u'defined_tags': {u'operations': {u'costcenter': u'10240', u'creator': u'"xxxxx at 2020-01-29T02:25:02.615Z"'}}, u'freeform_tags': {}, u'time_created': u'2020-01-29T02:25:02.702000+00:00', u'id': u'ocid1.compartment.oc1..aaaaaaaaqxxxx', u'description': u'DB compartment 2'}) => {"ansible_loop_var": "item", "changed": false, "item": {"compartment_id": "ocid1.compartment.oc1..aaaaaaaafxxxxx", "defined_tags": {"operations": {"costcenter": "10240", "creator": "\"xxxxxx at 2020-01-29T02:25:02.615Z\""}}, "description": "DB compartment 2", "freeform_tags": {}, "id": "ocid1.compartment.oc1..aaaaaaaaqxxxxxx", "inactive_status": null, "is_accessible": null, "lifecycle_state": "DELETED", "name": "dbcomp2.pIe8M9rc", "time_created": "2020-01-29T02:25:02.702000+00:00"}, "msg": "Authorization failed. For help with your user permissions, contact your tenancy's IAM administrator. Learn more:\nhttps://docs.cloud.oracle.com/iaas/Content/Identity/Reference/databasepolicyreference.htm"}
```
